CREATE TABLE car_shop
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    adress      VARCHAR(255),
    owner       VARCHAR(255),
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    CONSTRAINT pk_carshop PRIMARY KEY (id)
);

CREATE TABLE technic
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    surname     VARCHAR(255),
    speciality  VARCHAR(255),
    city        VARCHAR(255),
    review      DOUBLE PRECISION,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    CONSTRAINT pk_technic PRIMARY KEY (id)
);

CREATE TABLE car_shop_techics
(
    car_shop_id BIGINT NOT NULL,
    technic_id  BIGINT NOT NULL,
    CONSTRAINT pk_car_shop_techics PRIMARY KEY (car_shop_id, technic_id)
);

ALTER TABLE car_shop_techics
    ADD CONSTRAINT uc_car_shop_techics_technic UNIQUE (technic_id);

ALTER TABLE car_shop_techics
    ADD CONSTRAINT fk_carshotec_on_car_shop FOREIGN KEY (car_shop_id) REFERENCES car_shop (id);

ALTER TABLE car_shop_techics
    ADD CONSTRAINT fk_carshotec_on_technic FOREIGN KEY (technic_id) REFERENCES technic (id);