CREATE TABLE car_shop
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    adress      VARCHAR(255),
    owner       VARCHAR(255),
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    CONSTRAINT pk_carshop PRIMARY KEY (id)
);

CREATE TABLE technic
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    surname     VARCHAR(255),
    speciality  VARCHAR(255),
    city        VARCHAR(255),
    review      DOUBLE PRECISION,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    CONSTRAINT pk_technic PRIMARY KEY (id)
);

CREATE TABLE car_shop_techics
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    car_shop_id BIGINT,
    technic_id  BIGINT,
    CONSTRAINT pk_car_shop_techics PRIMARY KEY (id)
);

ALTER TABLE car_shop_techics
    ADD CONSTRAINT FK_CAR_SHOP_TECHICS_ON_CAR_SHOP FOREIGN KEY (car_shop_id) REFERENCES car_shop (id);

ALTER TABLE car_shop_techics
    ADD CONSTRAINT FK_CAR_SHOP_TECHICS_ON_TECHNIC FOREIGN KEY (technic_id) REFERENCES technic (id);